// Generated by CoffeeScript 1.7.1
var Ikagaka;

Ikagaka = (function() {
  function Ikagaka() {
    var hoge;
    hoge = 0;
  }

  return Ikagaka;

})();

if ((typeof module !== "undefined" && module !== null ? module.exports : void 0) != null) {
  module.exports = Ikagaka;
}

window["Ikagaka"] = Ikagaka;

require("ikagaka.nar.js");

require("ikagaka.shell.js");

require("ikagaka.balloon.js");

require("ikagaka.named.js");

require("ikagaka.sakurascriptplayer.js");

require("ikagaka.ghost.js");
