// Generated by CoffeeScript 1.7.1
var Balloon;

Balloon = (function() {
  function Balloon(shell) {
    this.shell = shell;
    this.$balloon = $("<div />").addClass("box");
    this.$style = $("<style scoped />").html(".box {\n  position: absolute;\n  top: -150px;\n  left: 0px;\n  height: 150px;\n  width: 280px;\n  background: #ccc;\n  overflow-y: scroll;\n  white-space: pre;\n  white-space: pre-wrap;\n  white-space: pre-line;\n  word-wrap: break-word;\n}\n.text {\n  padding: 1em;\n}\n.anchor,\n.select {\n  color:red;\n  cursor:pointer;\n}\n.anchor:hover,\n.select:hover {\n  background-color:violet;\n}");
    this.$text = $("<div />").addClass("text");
    this.$balloon.append(this.$style).append(this.$text);
    this.element = this.$balloon[0];
  }

  Balloon.prototype.talk = function(text) {
    this.$text.html(this.$text.html() + text);
    return void 0;
  };

  Balloon.prototype.clear = function() {
    this.$text.html("");
    return void 0;
  };

  Balloon.prototype.br = function() {
    this.talk("<br />");
    return void 0;
  };

  return Balloon;

})();
