// Generated by CoffeeScript 1.7.1
var Ghost;

Ghost = (function() {
  function Ghost(nar) {
    this.nar = nar;
  }

  Ghost.prototype.load = function(name, callback) {
    return callback();
  };

  Ghost.prototype.request = function() {};

  Ghost.prototype.unload = function() {};

  return Ghost;

})();
